import type { Metadata } from 'next'

import { cn } from '@/lib/utils'

import { Noto_Sans_SC } from 'next/font/google';

const notoSansSC = Noto_Sans_SC({
  weight: ['400', '900'], // 你可以根据需要选择不同的字体粗细
  subsets: ['latin-ext'], // 简体中文
});
export const metadata: Metadata = {
  title: 'Login',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div
      className={cn(
        'flex flex-col items-center justify-center min-h-screen py-2 bg-gradient-to-r from-orange-400 to-gray-400',
        { notoSansSC }
      )}
    >
      {children}
    </div>
  )
}
